;buildInfoPackage: chisel3, version: 3.4.1, scalaVersion: 2.12.12, sbtVersion: 1.3.10
circuit booth_div_substep : 
  module xor2 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_1 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_2 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_3 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_4 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_5 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_6 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_7 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_8 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_9 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_10 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_11 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_12 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_13 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_14 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_15 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_16 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_17 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_18 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_19 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_20 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_21 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_22 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_23 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_24 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_25 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_26 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_27 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_28 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_29 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_30 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module xor2_31 : 
    input clock : Clock
    input reset : Reset
    output io : {flip a : UInt<1>, flip b : UInt<1>, out : UInt<1>}
    
    node _T = xor(io.a, io.b) @[getOnesComplement.scala 13:20]
    io.out <= _T @[getOnesComplement.scala 13:12]
    
  module getOnesComplement : 
    input clock : Clock
    input reset : Reset
    output io : {flip cin : UInt<1>, flip i1 : UInt<32>, onesComp : UInt<32>}
    
    inst xor_0 of xor2 @[getOnesComplement.scala 24:33]
    xor_0.clock <= clock
    xor_0.reset <= reset
    inst xor_1 of xor2_1 @[getOnesComplement.scala 24:33]
    xor_1.clock <= clock
    xor_1.reset <= reset
    inst xor_2 of xor2_2 @[getOnesComplement.scala 24:33]
    xor_2.clock <= clock
    xor_2.reset <= reset
    inst xor_3 of xor2_3 @[getOnesComplement.scala 24:33]
    xor_3.clock <= clock
    xor_3.reset <= reset
    inst xor_4 of xor2_4 @[getOnesComplement.scala 24:33]
    xor_4.clock <= clock
    xor_4.reset <= reset
    inst xor_5 of xor2_5 @[getOnesComplement.scala 24:33]
    xor_5.clock <= clock
    xor_5.reset <= reset
    inst xor_6 of xor2_6 @[getOnesComplement.scala 24:33]
    xor_6.clock <= clock
    xor_6.reset <= reset
    inst xor_7 of xor2_7 @[getOnesComplement.scala 24:33]
    xor_7.clock <= clock
    xor_7.reset <= reset
    inst xor_8 of xor2_8 @[getOnesComplement.scala 24:33]
    xor_8.clock <= clock
    xor_8.reset <= reset
    inst xor_9 of xor2_9 @[getOnesComplement.scala 24:33]
    xor_9.clock <= clock
    xor_9.reset <= reset
    inst xor_10 of xor2_10 @[getOnesComplement.scala 24:33]
    xor_10.clock <= clock
    xor_10.reset <= reset
    inst xor_11 of xor2_11 @[getOnesComplement.scala 24:33]
    xor_11.clock <= clock
    xor_11.reset <= reset
    inst xor_12 of xor2_12 @[getOnesComplement.scala 24:33]
    xor_12.clock <= clock
    xor_12.reset <= reset
    inst xor_13 of xor2_13 @[getOnesComplement.scala 24:33]
    xor_13.clock <= clock
    xor_13.reset <= reset
    inst xor_14 of xor2_14 @[getOnesComplement.scala 24:33]
    xor_14.clock <= clock
    xor_14.reset <= reset
    inst xor_15 of xor2_15 @[getOnesComplement.scala 24:33]
    xor_15.clock <= clock
    xor_15.reset <= reset
    inst xor_16 of xor2_16 @[getOnesComplement.scala 24:33]
    xor_16.clock <= clock
    xor_16.reset <= reset
    inst xor_17 of xor2_17 @[getOnesComplement.scala 24:33]
    xor_17.clock <= clock
    xor_17.reset <= reset
    inst xor_18 of xor2_18 @[getOnesComplement.scala 24:33]
    xor_18.clock <= clock
    xor_18.reset <= reset
    inst xor_19 of xor2_19 @[getOnesComplement.scala 24:33]
    xor_19.clock <= clock
    xor_19.reset <= reset
    inst xor_20 of xor2_20 @[getOnesComplement.scala 24:33]
    xor_20.clock <= clock
    xor_20.reset <= reset
    inst xor_21 of xor2_21 @[getOnesComplement.scala 24:33]
    xor_21.clock <= clock
    xor_21.reset <= reset
    inst xor_22 of xor2_22 @[getOnesComplement.scala 24:33]
    xor_22.clock <= clock
    xor_22.reset <= reset
    inst xor_23 of xor2_23 @[getOnesComplement.scala 24:33]
    xor_23.clock <= clock
    xor_23.reset <= reset
    inst xor_24 of xor2_24 @[getOnesComplement.scala 24:33]
    xor_24.clock <= clock
    xor_24.reset <= reset
    inst xor_25 of xor2_25 @[getOnesComplement.scala 24:33]
    xor_25.clock <= clock
    xor_25.reset <= reset
    inst xor_26 of xor2_26 @[getOnesComplement.scala 24:33]
    xor_26.clock <= clock
    xor_26.reset <= reset
    inst xor_27 of xor2_27 @[getOnesComplement.scala 24:33]
    xor_27.clock <= clock
    xor_27.reset <= reset
    inst xor_28 of xor2_28 @[getOnesComplement.scala 24:33]
    xor_28.clock <= clock
    xor_28.reset <= reset
    inst xor_29 of xor2_29 @[getOnesComplement.scala 24:33]
    xor_29.clock <= clock
    xor_29.reset <= reset
    inst xor_30 of xor2_30 @[getOnesComplement.scala 24:33]
    xor_30.clock <= clock
    xor_30.reset <= reset
    inst xor_31 of xor2_31 @[getOnesComplement.scala 24:33]
    xor_31.clock <= clock
    xor_31.reset <= reset
    node _T = bits(io.i1, 0, 0) @[getOnesComplement.scala 27:29]
    xor_0.io.a <= _T @[getOnesComplement.scala 27:21]
    xor_0.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_1 = bits(io.i1, 1, 1) @[getOnesComplement.scala 27:29]
    xor_1.io.a <= _T_1 @[getOnesComplement.scala 27:21]
    xor_1.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_2 = bits(io.i1, 2, 2) @[getOnesComplement.scala 27:29]
    xor_2.io.a <= _T_2 @[getOnesComplement.scala 27:21]
    xor_2.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_3 = bits(io.i1, 3, 3) @[getOnesComplement.scala 27:29]
    xor_3.io.a <= _T_3 @[getOnesComplement.scala 27:21]
    xor_3.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_4 = bits(io.i1, 4, 4) @[getOnesComplement.scala 27:29]
    xor_4.io.a <= _T_4 @[getOnesComplement.scala 27:21]
    xor_4.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_5 = bits(io.i1, 5, 5) @[getOnesComplement.scala 27:29]
    xor_5.io.a <= _T_5 @[getOnesComplement.scala 27:21]
    xor_5.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_6 = bits(io.i1, 6, 6) @[getOnesComplement.scala 27:29]
    xor_6.io.a <= _T_6 @[getOnesComplement.scala 27:21]
    xor_6.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_7 = bits(io.i1, 7, 7) @[getOnesComplement.scala 27:29]
    xor_7.io.a <= _T_7 @[getOnesComplement.scala 27:21]
    xor_7.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_8 = bits(io.i1, 8, 8) @[getOnesComplement.scala 27:29]
    xor_8.io.a <= _T_8 @[getOnesComplement.scala 27:21]
    xor_8.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_9 = bits(io.i1, 9, 9) @[getOnesComplement.scala 27:29]
    xor_9.io.a <= _T_9 @[getOnesComplement.scala 27:21]
    xor_9.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_10 = bits(io.i1, 10, 10) @[getOnesComplement.scala 27:29]
    xor_10.io.a <= _T_10 @[getOnesComplement.scala 27:21]
    xor_10.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_11 = bits(io.i1, 11, 11) @[getOnesComplement.scala 27:29]
    xor_11.io.a <= _T_11 @[getOnesComplement.scala 27:21]
    xor_11.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_12 = bits(io.i1, 12, 12) @[getOnesComplement.scala 27:29]
    xor_12.io.a <= _T_12 @[getOnesComplement.scala 27:21]
    xor_12.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_13 = bits(io.i1, 13, 13) @[getOnesComplement.scala 27:29]
    xor_13.io.a <= _T_13 @[getOnesComplement.scala 27:21]
    xor_13.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_14 = bits(io.i1, 14, 14) @[getOnesComplement.scala 27:29]
    xor_14.io.a <= _T_14 @[getOnesComplement.scala 27:21]
    xor_14.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_15 = bits(io.i1, 15, 15) @[getOnesComplement.scala 27:29]
    xor_15.io.a <= _T_15 @[getOnesComplement.scala 27:21]
    xor_15.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_16 = bits(io.i1, 16, 16) @[getOnesComplement.scala 27:29]
    xor_16.io.a <= _T_16 @[getOnesComplement.scala 27:21]
    xor_16.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_17 = bits(io.i1, 17, 17) @[getOnesComplement.scala 27:29]
    xor_17.io.a <= _T_17 @[getOnesComplement.scala 27:21]
    xor_17.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_18 = bits(io.i1, 18, 18) @[getOnesComplement.scala 27:29]
    xor_18.io.a <= _T_18 @[getOnesComplement.scala 27:21]
    xor_18.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_19 = bits(io.i1, 19, 19) @[getOnesComplement.scala 27:29]
    xor_19.io.a <= _T_19 @[getOnesComplement.scala 27:21]
    xor_19.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_20 = bits(io.i1, 20, 20) @[getOnesComplement.scala 27:29]
    xor_20.io.a <= _T_20 @[getOnesComplement.scala 27:21]
    xor_20.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_21 = bits(io.i1, 21, 21) @[getOnesComplement.scala 27:29]
    xor_21.io.a <= _T_21 @[getOnesComplement.scala 27:21]
    xor_21.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_22 = bits(io.i1, 22, 22) @[getOnesComplement.scala 27:29]
    xor_22.io.a <= _T_22 @[getOnesComplement.scala 27:21]
    xor_22.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_23 = bits(io.i1, 23, 23) @[getOnesComplement.scala 27:29]
    xor_23.io.a <= _T_23 @[getOnesComplement.scala 27:21]
    xor_23.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_24 = bits(io.i1, 24, 24) @[getOnesComplement.scala 27:29]
    xor_24.io.a <= _T_24 @[getOnesComplement.scala 27:21]
    xor_24.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_25 = bits(io.i1, 25, 25) @[getOnesComplement.scala 27:29]
    xor_25.io.a <= _T_25 @[getOnesComplement.scala 27:21]
    xor_25.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_26 = bits(io.i1, 26, 26) @[getOnesComplement.scala 27:29]
    xor_26.io.a <= _T_26 @[getOnesComplement.scala 27:21]
    xor_26.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_27 = bits(io.i1, 27, 27) @[getOnesComplement.scala 27:29]
    xor_27.io.a <= _T_27 @[getOnesComplement.scala 27:21]
    xor_27.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_28 = bits(io.i1, 28, 28) @[getOnesComplement.scala 27:29]
    xor_28.io.a <= _T_28 @[getOnesComplement.scala 27:21]
    xor_28.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_29 = bits(io.i1, 29, 29) @[getOnesComplement.scala 27:29]
    xor_29.io.a <= _T_29 @[getOnesComplement.scala 27:21]
    xor_29.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_30 = bits(io.i1, 30, 30) @[getOnesComplement.scala 27:29]
    xor_30.io.a <= _T_30 @[getOnesComplement.scala 27:21]
    xor_30.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node _T_31 = bits(io.i1, 31, 31) @[getOnesComplement.scala 27:29]
    xor_31.io.a <= _T_31 @[getOnesComplement.scala 27:21]
    xor_31.io.b <= io.cin @[getOnesComplement.scala 28:21]
    node lo_lo_lo_lo = cat(xor_1.io.out, xor_0.io.out) @[Cat.scala 30:58]
    node lo_lo_lo_hi = cat(xor_3.io.out, xor_2.io.out) @[Cat.scala 30:58]
    node lo_lo_lo = cat(lo_lo_lo_hi, lo_lo_lo_lo) @[Cat.scala 30:58]
    node lo_lo_hi_lo = cat(xor_5.io.out, xor_4.io.out) @[Cat.scala 30:58]
    node lo_lo_hi_hi = cat(xor_7.io.out, xor_6.io.out) @[Cat.scala 30:58]
    node lo_lo_hi = cat(lo_lo_hi_hi, lo_lo_hi_lo) @[Cat.scala 30:58]
    node lo_lo = cat(lo_lo_hi, lo_lo_lo) @[Cat.scala 30:58]
    node lo_hi_lo_lo = cat(xor_9.io.out, xor_8.io.out) @[Cat.scala 30:58]
    node lo_hi_lo_hi = cat(xor_11.io.out, xor_10.io.out) @[Cat.scala 30:58]
    node lo_hi_lo = cat(lo_hi_lo_hi, lo_hi_lo_lo) @[Cat.scala 30:58]
    node lo_hi_hi_lo = cat(xor_13.io.out, xor_12.io.out) @[Cat.scala 30:58]
    node lo_hi_hi_hi = cat(xor_15.io.out, xor_14.io.out) @[Cat.scala 30:58]
    node lo_hi_hi = cat(lo_hi_hi_hi, lo_hi_hi_lo) @[Cat.scala 30:58]
    node lo_hi = cat(lo_hi_hi, lo_hi_lo) @[Cat.scala 30:58]
    node lo = cat(lo_hi, lo_lo) @[Cat.scala 30:58]
    node hi_lo_lo_lo = cat(xor_17.io.out, xor_16.io.out) @[Cat.scala 30:58]
    node hi_lo_lo_hi = cat(xor_19.io.out, xor_18.io.out) @[Cat.scala 30:58]
    node hi_lo_lo = cat(hi_lo_lo_hi, hi_lo_lo_lo) @[Cat.scala 30:58]
    node hi_lo_hi_lo = cat(xor_21.io.out, xor_20.io.out) @[Cat.scala 30:58]
    node hi_lo_hi_hi = cat(xor_23.io.out, xor_22.io.out) @[Cat.scala 30:58]
    node hi_lo_hi = cat(hi_lo_hi_hi, hi_lo_hi_lo) @[Cat.scala 30:58]
    node hi_lo = cat(hi_lo_hi, hi_lo_lo) @[Cat.scala 30:58]
    node hi_hi_lo_lo = cat(xor_25.io.out, xor_24.io.out) @[Cat.scala 30:58]
    node hi_hi_lo_hi = cat(xor_27.io.out, xor_26.io.out) @[Cat.scala 30:58]
    node hi_hi_lo = cat(hi_hi_lo_hi, hi_hi_lo_lo) @[Cat.scala 30:58]
    node hi_hi_hi_lo = cat(xor_29.io.out, xor_28.io.out) @[Cat.scala 30:58]
    node hi_hi_hi_hi = cat(xor_31.io.out, xor_30.io.out) @[Cat.scala 30:58]
    node hi_hi_hi = cat(hi_hi_hi_hi, hi_hi_hi_lo) @[Cat.scala 30:58]
    node hi_hi = cat(hi_hi_hi, hi_hi_lo) @[Cat.scala 30:58]
    node hi = cat(hi_hi, hi_lo) @[Cat.scala 30:58]
    node _T_32 = cat(hi, lo) @[Cat.scala 30:58]
    io.onesComp <= _T_32 @[getOnesComplement.scala 32:17]
    
  module fullAdder : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_1 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_2 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_3 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_4 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_5 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_6 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_7 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_8 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_9 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_10 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_11 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_12 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_13 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_14 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_15 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_16 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_17 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_18 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_19 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_20 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_21 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_22 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_23 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_24 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_25 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_26 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_27 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_28 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_29 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_30 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module fullAdder_31 : 
    input clock : Clock
    input reset : Reset
    output io : {flip i0 : UInt<1>, flip i1 : UInt<1>, flip cin : UInt<1>, sum : UInt<1>, cout : UInt<1>}
    
    node _T = xor(io.i0, io.i1) @[addsub_64.scala 14:21]
    node _T_1 = xor(_T, io.cin) @[addsub_64.scala 14:29]
    io.sum <= _T_1 @[addsub_64.scala 14:12]
    node _T_2 = and(io.i0, io.i1) @[addsub_64.scala 15:23]
    node _T_3 = and(io.i1, io.cin) @[addsub_64.scala 15:41]
    node _T_4 = or(_T_2, _T_3) @[addsub_64.scala 15:32]
    node _T_5 = and(io.cin, io.i0) @[addsub_64.scala 15:61]
    node _T_6 = or(_T_4, _T_5) @[addsub_64.scala 15:51]
    io.cout <= _T_6 @[addsub_64.scala 15:13]
    
  module addsub_32 : 
    input clock : Clock
    input reset : Reset
    output io : {flip cin : UInt<1>, flip onesComp_ip : UInt<32>, flip i0 : UInt<32>, sum : UInt<32>, cout : UInt<1>}
    
    inst fa_0 of fullAdder @[addsub_32.scala 14:33]
    fa_0.clock <= clock
    fa_0.reset <= reset
    inst fa_1 of fullAdder_1 @[addsub_32.scala 14:33]
    fa_1.clock <= clock
    fa_1.reset <= reset
    inst fa_2 of fullAdder_2 @[addsub_32.scala 14:33]
    fa_2.clock <= clock
    fa_2.reset <= reset
    inst fa_3 of fullAdder_3 @[addsub_32.scala 14:33]
    fa_3.clock <= clock
    fa_3.reset <= reset
    inst fa_4 of fullAdder_4 @[addsub_32.scala 14:33]
    fa_4.clock <= clock
    fa_4.reset <= reset
    inst fa_5 of fullAdder_5 @[addsub_32.scala 14:33]
    fa_5.clock <= clock
    fa_5.reset <= reset
    inst fa_6 of fullAdder_6 @[addsub_32.scala 14:33]
    fa_6.clock <= clock
    fa_6.reset <= reset
    inst fa_7 of fullAdder_7 @[addsub_32.scala 14:33]
    fa_7.clock <= clock
    fa_7.reset <= reset
    inst fa_8 of fullAdder_8 @[addsub_32.scala 14:33]
    fa_8.clock <= clock
    fa_8.reset <= reset
    inst fa_9 of fullAdder_9 @[addsub_32.scala 14:33]
    fa_9.clock <= clock
    fa_9.reset <= reset
    inst fa_10 of fullAdder_10 @[addsub_32.scala 14:33]
    fa_10.clock <= clock
    fa_10.reset <= reset
    inst fa_11 of fullAdder_11 @[addsub_32.scala 14:33]
    fa_11.clock <= clock
    fa_11.reset <= reset
    inst fa_12 of fullAdder_12 @[addsub_32.scala 14:33]
    fa_12.clock <= clock
    fa_12.reset <= reset
    inst fa_13 of fullAdder_13 @[addsub_32.scala 14:33]
    fa_13.clock <= clock
    fa_13.reset <= reset
    inst fa_14 of fullAdder_14 @[addsub_32.scala 14:33]
    fa_14.clock <= clock
    fa_14.reset <= reset
    inst fa_15 of fullAdder_15 @[addsub_32.scala 14:33]
    fa_15.clock <= clock
    fa_15.reset <= reset
    inst fa_16 of fullAdder_16 @[addsub_32.scala 14:33]
    fa_16.clock <= clock
    fa_16.reset <= reset
    inst fa_17 of fullAdder_17 @[addsub_32.scala 14:33]
    fa_17.clock <= clock
    fa_17.reset <= reset
    inst fa_18 of fullAdder_18 @[addsub_32.scala 14:33]
    fa_18.clock <= clock
    fa_18.reset <= reset
    inst fa_19 of fullAdder_19 @[addsub_32.scala 14:33]
    fa_19.clock <= clock
    fa_19.reset <= reset
    inst fa_20 of fullAdder_20 @[addsub_32.scala 14:33]
    fa_20.clock <= clock
    fa_20.reset <= reset
    inst fa_21 of fullAdder_21 @[addsub_32.scala 14:33]
    fa_21.clock <= clock
    fa_21.reset <= reset
    inst fa_22 of fullAdder_22 @[addsub_32.scala 14:33]
    fa_22.clock <= clock
    fa_22.reset <= reset
    inst fa_23 of fullAdder_23 @[addsub_32.scala 14:33]
    fa_23.clock <= clock
    fa_23.reset <= reset
    inst fa_24 of fullAdder_24 @[addsub_32.scala 14:33]
    fa_24.clock <= clock
    fa_24.reset <= reset
    inst fa_25 of fullAdder_25 @[addsub_32.scala 14:33]
    fa_25.clock <= clock
    fa_25.reset <= reset
    inst fa_26 of fullAdder_26 @[addsub_32.scala 14:33]
    fa_26.clock <= clock
    fa_26.reset <= reset
    inst fa_27 of fullAdder_27 @[addsub_32.scala 14:33]
    fa_27.clock <= clock
    fa_27.reset <= reset
    inst fa_28 of fullAdder_28 @[addsub_32.scala 14:33]
    fa_28.clock <= clock
    fa_28.reset <= reset
    inst fa_29 of fullAdder_29 @[addsub_32.scala 14:33]
    fa_29.clock <= clock
    fa_29.reset <= reset
    inst fa_30 of fullAdder_30 @[addsub_32.scala 14:33]
    fa_30.clock <= clock
    fa_30.reset <= reset
    inst fa_31 of fullAdder_31 @[addsub_32.scala 14:33]
    fa_31.clock <= clock
    fa_31.reset <= reset
    node _T = bits(io.i0, 0, 0) @[addsub_32.scala 17:25]
    fa_0.io.i0 <= _T @[addsub_32.scala 17:17]
    node _T_1 = bits(io.onesComp_ip, 0, 0) @[addsub_32.scala 18:34]
    fa_0.io.i1 <= _T_1 @[addsub_32.scala 18:17]
    fa_0.io.cin <= io.cin @[addsub_32.scala 19:18]
    node _T_2 = bits(io.i0, 1, 1) @[addsub_32.scala 23:29]
    fa_1.io.i0 <= _T_2 @[addsub_32.scala 23:21]
    node _T_3 = bits(io.onesComp_ip, 1, 1) @[addsub_32.scala 24:38]
    fa_1.io.i1 <= _T_3 @[addsub_32.scala 24:21]
    fa_1.io.cin <= fa_0.io.cout @[addsub_32.scala 25:22]
    node _T_4 = bits(io.i0, 2, 2) @[addsub_32.scala 23:29]
    fa_2.io.i0 <= _T_4 @[addsub_32.scala 23:21]
    node _T_5 = bits(io.onesComp_ip, 2, 2) @[addsub_32.scala 24:38]
    fa_2.io.i1 <= _T_5 @[addsub_32.scala 24:21]
    fa_2.io.cin <= fa_1.io.cout @[addsub_32.scala 25:22]
    node _T_6 = bits(io.i0, 3, 3) @[addsub_32.scala 23:29]
    fa_3.io.i0 <= _T_6 @[addsub_32.scala 23:21]
    node _T_7 = bits(io.onesComp_ip, 3, 3) @[addsub_32.scala 24:38]
    fa_3.io.i1 <= _T_7 @[addsub_32.scala 24:21]
    fa_3.io.cin <= fa_2.io.cout @[addsub_32.scala 25:22]
    node _T_8 = bits(io.i0, 4, 4) @[addsub_32.scala 23:29]
    fa_4.io.i0 <= _T_8 @[addsub_32.scala 23:21]
    node _T_9 = bits(io.onesComp_ip, 4, 4) @[addsub_32.scala 24:38]
    fa_4.io.i1 <= _T_9 @[addsub_32.scala 24:21]
    fa_4.io.cin <= fa_3.io.cout @[addsub_32.scala 25:22]
    node _T_10 = bits(io.i0, 5, 5) @[addsub_32.scala 23:29]
    fa_5.io.i0 <= _T_10 @[addsub_32.scala 23:21]
    node _T_11 = bits(io.onesComp_ip, 5, 5) @[addsub_32.scala 24:38]
    fa_5.io.i1 <= _T_11 @[addsub_32.scala 24:21]
    fa_5.io.cin <= fa_4.io.cout @[addsub_32.scala 25:22]
    node _T_12 = bits(io.i0, 6, 6) @[addsub_32.scala 23:29]
    fa_6.io.i0 <= _T_12 @[addsub_32.scala 23:21]
    node _T_13 = bits(io.onesComp_ip, 6, 6) @[addsub_32.scala 24:38]
    fa_6.io.i1 <= _T_13 @[addsub_32.scala 24:21]
    fa_6.io.cin <= fa_5.io.cout @[addsub_32.scala 25:22]
    node _T_14 = bits(io.i0, 7, 7) @[addsub_32.scala 23:29]
    fa_7.io.i0 <= _T_14 @[addsub_32.scala 23:21]
    node _T_15 = bits(io.onesComp_ip, 7, 7) @[addsub_32.scala 24:38]
    fa_7.io.i1 <= _T_15 @[addsub_32.scala 24:21]
    fa_7.io.cin <= fa_6.io.cout @[addsub_32.scala 25:22]
    node _T_16 = bits(io.i0, 8, 8) @[addsub_32.scala 23:29]
    fa_8.io.i0 <= _T_16 @[addsub_32.scala 23:21]
    node _T_17 = bits(io.onesComp_ip, 8, 8) @[addsub_32.scala 24:38]
    fa_8.io.i1 <= _T_17 @[addsub_32.scala 24:21]
    fa_8.io.cin <= fa_7.io.cout @[addsub_32.scala 25:22]
    node _T_18 = bits(io.i0, 9, 9) @[addsub_32.scala 23:29]
    fa_9.io.i0 <= _T_18 @[addsub_32.scala 23:21]
    node _T_19 = bits(io.onesComp_ip, 9, 9) @[addsub_32.scala 24:38]
    fa_9.io.i1 <= _T_19 @[addsub_32.scala 24:21]
    fa_9.io.cin <= fa_8.io.cout @[addsub_32.scala 25:22]
    node _T_20 = bits(io.i0, 10, 10) @[addsub_32.scala 23:29]
    fa_10.io.i0 <= _T_20 @[addsub_32.scala 23:21]
    node _T_21 = bits(io.onesComp_ip, 10, 10) @[addsub_32.scala 24:38]
    fa_10.io.i1 <= _T_21 @[addsub_32.scala 24:21]
    fa_10.io.cin <= fa_9.io.cout @[addsub_32.scala 25:22]
    node _T_22 = bits(io.i0, 11, 11) @[addsub_32.scala 23:29]
    fa_11.io.i0 <= _T_22 @[addsub_32.scala 23:21]
    node _T_23 = bits(io.onesComp_ip, 11, 11) @[addsub_32.scala 24:38]
    fa_11.io.i1 <= _T_23 @[addsub_32.scala 24:21]
    fa_11.io.cin <= fa_10.io.cout @[addsub_32.scala 25:22]
    node _T_24 = bits(io.i0, 12, 12) @[addsub_32.scala 23:29]
    fa_12.io.i0 <= _T_24 @[addsub_32.scala 23:21]
    node _T_25 = bits(io.onesComp_ip, 12, 12) @[addsub_32.scala 24:38]
    fa_12.io.i1 <= _T_25 @[addsub_32.scala 24:21]
    fa_12.io.cin <= fa_11.io.cout @[addsub_32.scala 25:22]
    node _T_26 = bits(io.i0, 13, 13) @[addsub_32.scala 23:29]
    fa_13.io.i0 <= _T_26 @[addsub_32.scala 23:21]
    node _T_27 = bits(io.onesComp_ip, 13, 13) @[addsub_32.scala 24:38]
    fa_13.io.i1 <= _T_27 @[addsub_32.scala 24:21]
    fa_13.io.cin <= fa_12.io.cout @[addsub_32.scala 25:22]
    node _T_28 = bits(io.i0, 14, 14) @[addsub_32.scala 23:29]
    fa_14.io.i0 <= _T_28 @[addsub_32.scala 23:21]
    node _T_29 = bits(io.onesComp_ip, 14, 14) @[addsub_32.scala 24:38]
    fa_14.io.i1 <= _T_29 @[addsub_32.scala 24:21]
    fa_14.io.cin <= fa_13.io.cout @[addsub_32.scala 25:22]
    node _T_30 = bits(io.i0, 15, 15) @[addsub_32.scala 23:29]
    fa_15.io.i0 <= _T_30 @[addsub_32.scala 23:21]
    node _T_31 = bits(io.onesComp_ip, 15, 15) @[addsub_32.scala 24:38]
    fa_15.io.i1 <= _T_31 @[addsub_32.scala 24:21]
    fa_15.io.cin <= fa_14.io.cout @[addsub_32.scala 25:22]
    node _T_32 = bits(io.i0, 16, 16) @[addsub_32.scala 23:29]
    fa_16.io.i0 <= _T_32 @[addsub_32.scala 23:21]
    node _T_33 = bits(io.onesComp_ip, 16, 16) @[addsub_32.scala 24:38]
    fa_16.io.i1 <= _T_33 @[addsub_32.scala 24:21]
    fa_16.io.cin <= fa_15.io.cout @[addsub_32.scala 25:22]
    node _T_34 = bits(io.i0, 17, 17) @[addsub_32.scala 23:29]
    fa_17.io.i0 <= _T_34 @[addsub_32.scala 23:21]
    node _T_35 = bits(io.onesComp_ip, 17, 17) @[addsub_32.scala 24:38]
    fa_17.io.i1 <= _T_35 @[addsub_32.scala 24:21]
    fa_17.io.cin <= fa_16.io.cout @[addsub_32.scala 25:22]
    node _T_36 = bits(io.i0, 18, 18) @[addsub_32.scala 23:29]
    fa_18.io.i0 <= _T_36 @[addsub_32.scala 23:21]
    node _T_37 = bits(io.onesComp_ip, 18, 18) @[addsub_32.scala 24:38]
    fa_18.io.i1 <= _T_37 @[addsub_32.scala 24:21]
    fa_18.io.cin <= fa_17.io.cout @[addsub_32.scala 25:22]
    node _T_38 = bits(io.i0, 19, 19) @[addsub_32.scala 23:29]
    fa_19.io.i0 <= _T_38 @[addsub_32.scala 23:21]
    node _T_39 = bits(io.onesComp_ip, 19, 19) @[addsub_32.scala 24:38]
    fa_19.io.i1 <= _T_39 @[addsub_32.scala 24:21]
    fa_19.io.cin <= fa_18.io.cout @[addsub_32.scala 25:22]
    node _T_40 = bits(io.i0, 20, 20) @[addsub_32.scala 23:29]
    fa_20.io.i0 <= _T_40 @[addsub_32.scala 23:21]
    node _T_41 = bits(io.onesComp_ip, 20, 20) @[addsub_32.scala 24:38]
    fa_20.io.i1 <= _T_41 @[addsub_32.scala 24:21]
    fa_20.io.cin <= fa_19.io.cout @[addsub_32.scala 25:22]
    node _T_42 = bits(io.i0, 21, 21) @[addsub_32.scala 23:29]
    fa_21.io.i0 <= _T_42 @[addsub_32.scala 23:21]
    node _T_43 = bits(io.onesComp_ip, 21, 21) @[addsub_32.scala 24:38]
    fa_21.io.i1 <= _T_43 @[addsub_32.scala 24:21]
    fa_21.io.cin <= fa_20.io.cout @[addsub_32.scala 25:22]
    node _T_44 = bits(io.i0, 22, 22) @[addsub_32.scala 23:29]
    fa_22.io.i0 <= _T_44 @[addsub_32.scala 23:21]
    node _T_45 = bits(io.onesComp_ip, 22, 22) @[addsub_32.scala 24:38]
    fa_22.io.i1 <= _T_45 @[addsub_32.scala 24:21]
    fa_22.io.cin <= fa_21.io.cout @[addsub_32.scala 25:22]
    node _T_46 = bits(io.i0, 23, 23) @[addsub_32.scala 23:29]
    fa_23.io.i0 <= _T_46 @[addsub_32.scala 23:21]
    node _T_47 = bits(io.onesComp_ip, 23, 23) @[addsub_32.scala 24:38]
    fa_23.io.i1 <= _T_47 @[addsub_32.scala 24:21]
    fa_23.io.cin <= fa_22.io.cout @[addsub_32.scala 25:22]
    node _T_48 = bits(io.i0, 24, 24) @[addsub_32.scala 23:29]
    fa_24.io.i0 <= _T_48 @[addsub_32.scala 23:21]
    node _T_49 = bits(io.onesComp_ip, 24, 24) @[addsub_32.scala 24:38]
    fa_24.io.i1 <= _T_49 @[addsub_32.scala 24:21]
    fa_24.io.cin <= fa_23.io.cout @[addsub_32.scala 25:22]
    node _T_50 = bits(io.i0, 25, 25) @[addsub_32.scala 23:29]
    fa_25.io.i0 <= _T_50 @[addsub_32.scala 23:21]
    node _T_51 = bits(io.onesComp_ip, 25, 25) @[addsub_32.scala 24:38]
    fa_25.io.i1 <= _T_51 @[addsub_32.scala 24:21]
    fa_25.io.cin <= fa_24.io.cout @[addsub_32.scala 25:22]
    node _T_52 = bits(io.i0, 26, 26) @[addsub_32.scala 23:29]
    fa_26.io.i0 <= _T_52 @[addsub_32.scala 23:21]
    node _T_53 = bits(io.onesComp_ip, 26, 26) @[addsub_32.scala 24:38]
    fa_26.io.i1 <= _T_53 @[addsub_32.scala 24:21]
    fa_26.io.cin <= fa_25.io.cout @[addsub_32.scala 25:22]
    node _T_54 = bits(io.i0, 27, 27) @[addsub_32.scala 23:29]
    fa_27.io.i0 <= _T_54 @[addsub_32.scala 23:21]
    node _T_55 = bits(io.onesComp_ip, 27, 27) @[addsub_32.scala 24:38]
    fa_27.io.i1 <= _T_55 @[addsub_32.scala 24:21]
    fa_27.io.cin <= fa_26.io.cout @[addsub_32.scala 25:22]
    node _T_56 = bits(io.i0, 28, 28) @[addsub_32.scala 23:29]
    fa_28.io.i0 <= _T_56 @[addsub_32.scala 23:21]
    node _T_57 = bits(io.onesComp_ip, 28, 28) @[addsub_32.scala 24:38]
    fa_28.io.i1 <= _T_57 @[addsub_32.scala 24:21]
    fa_28.io.cin <= fa_27.io.cout @[addsub_32.scala 25:22]
    node _T_58 = bits(io.i0, 29, 29) @[addsub_32.scala 23:29]
    fa_29.io.i0 <= _T_58 @[addsub_32.scala 23:21]
    node _T_59 = bits(io.onesComp_ip, 29, 29) @[addsub_32.scala 24:38]
    fa_29.io.i1 <= _T_59 @[addsub_32.scala 24:21]
    fa_29.io.cin <= fa_28.io.cout @[addsub_32.scala 25:22]
    node _T_60 = bits(io.i0, 30, 30) @[addsub_32.scala 23:29]
    fa_30.io.i0 <= _T_60 @[addsub_32.scala 23:21]
    node _T_61 = bits(io.onesComp_ip, 30, 30) @[addsub_32.scala 24:38]
    fa_30.io.i1 <= _T_61 @[addsub_32.scala 24:21]
    fa_30.io.cin <= fa_29.io.cout @[addsub_32.scala 25:22]
    node _T_62 = bits(io.i0, 31, 31) @[addsub_32.scala 23:29]
    fa_31.io.i0 <= _T_62 @[addsub_32.scala 23:21]
    node _T_63 = bits(io.onesComp_ip, 31, 31) @[addsub_32.scala 24:38]
    fa_31.io.i1 <= _T_63 @[addsub_32.scala 24:21]
    fa_31.io.cin <= fa_30.io.cout @[addsub_32.scala 25:22]
    node lo_lo_lo_lo = cat(fa_1.io.sum, fa_0.io.sum) @[Cat.scala 30:58]
    node lo_lo_lo_hi = cat(fa_3.io.sum, fa_2.io.sum) @[Cat.scala 30:58]
    node lo_lo_lo = cat(lo_lo_lo_hi, lo_lo_lo_lo) @[Cat.scala 30:58]
    node lo_lo_hi_lo = cat(fa_5.io.sum, fa_4.io.sum) @[Cat.scala 30:58]
    node lo_lo_hi_hi = cat(fa_7.io.sum, fa_6.io.sum) @[Cat.scala 30:58]
    node lo_lo_hi = cat(lo_lo_hi_hi, lo_lo_hi_lo) @[Cat.scala 30:58]
    node lo_lo = cat(lo_lo_hi, lo_lo_lo) @[Cat.scala 30:58]
    node lo_hi_lo_lo = cat(fa_9.io.sum, fa_8.io.sum) @[Cat.scala 30:58]
    node lo_hi_lo_hi = cat(fa_11.io.sum, fa_10.io.sum) @[Cat.scala 30:58]
    node lo_hi_lo = cat(lo_hi_lo_hi, lo_hi_lo_lo) @[Cat.scala 30:58]
    node lo_hi_hi_lo = cat(fa_13.io.sum, fa_12.io.sum) @[Cat.scala 30:58]
    node lo_hi_hi_hi = cat(fa_15.io.sum, fa_14.io.sum) @[Cat.scala 30:58]
    node lo_hi_hi = cat(lo_hi_hi_hi, lo_hi_hi_lo) @[Cat.scala 30:58]
    node lo_hi = cat(lo_hi_hi, lo_hi_lo) @[Cat.scala 30:58]
    node lo = cat(lo_hi, lo_lo) @[Cat.scala 30:58]
    node hi_lo_lo_lo = cat(fa_17.io.sum, fa_16.io.sum) @[Cat.scala 30:58]
    node hi_lo_lo_hi = cat(fa_19.io.sum, fa_18.io.sum) @[Cat.scala 30:58]
    node hi_lo_lo = cat(hi_lo_lo_hi, hi_lo_lo_lo) @[Cat.scala 30:58]
    node hi_lo_hi_lo = cat(fa_21.io.sum, fa_20.io.sum) @[Cat.scala 30:58]
    node hi_lo_hi_hi = cat(fa_23.io.sum, fa_22.io.sum) @[Cat.scala 30:58]
    node hi_lo_hi = cat(hi_lo_hi_hi, hi_lo_hi_lo) @[Cat.scala 30:58]
    node hi_lo = cat(hi_lo_hi, hi_lo_lo) @[Cat.scala 30:58]
    node hi_hi_lo_lo = cat(fa_25.io.sum, fa_24.io.sum) @[Cat.scala 30:58]
    node hi_hi_lo_hi = cat(fa_27.io.sum, fa_26.io.sum) @[Cat.scala 30:58]
    node hi_hi_lo = cat(hi_hi_lo_hi, hi_hi_lo_lo) @[Cat.scala 30:58]
    node hi_hi_hi_lo = cat(fa_29.io.sum, fa_28.io.sum) @[Cat.scala 30:58]
    node hi_hi_hi_hi = cat(fa_31.io.sum, fa_30.io.sum) @[Cat.scala 30:58]
    node hi_hi_hi = cat(hi_hi_hi_hi, hi_hi_hi_lo) @[Cat.scala 30:58]
    node hi_hi = cat(hi_hi_hi, hi_hi_lo) @[Cat.scala 30:58]
    node hi = cat(hi_hi, hi_lo) @[Cat.scala 30:58]
    node _T_64 = cat(hi, lo) @[Cat.scala 30:58]
    io.sum <= _T_64 @[addsub_32.scala 29:12]
    io.cout <= fa_31.io.cout @[addsub_32.scala 30:13]
    
  module booth_div_substep : 
    input clock : Clock
    input reset : UInt<1>
    output io : {flip acc : SInt<32>, flip Q : SInt<32>, flip divisor : SInt<32>, next_acc : SInt<32>, next_Q : SInt<32>}
    
    inst g1 of getOnesComplement @[booth_div_substep.scala 13:20]
    g1.clock <= clock
    g1.reset <= reset
    wire int_ip : UInt<32> @[booth_div_substep.scala 15:22]
    g1.io.cin <= UInt<1>("h01") @[booth_div_substep.scala 17:15]
    node _T = asUInt(io.divisor) @[booth_div_substep.scala 18:28]
    g1.io.i1 <= _T @[booth_div_substep.scala 18:14]
    int_ip <= g1.io.onesComp @[booth_div_substep.scala 19:12]
    wire shiftedA : UInt<33> @[booth_div_substep.scala 22:24]
    wire shiftedQ : UInt<33> @[booth_div_substep.scala 23:24]
    wire shiftedA_LSB : UInt<1> @[booth_div_substep.scala 24:28]
    wire shiftedQ_LSB : UInt<1> @[booth_div_substep.scala 25:28]
    wire Aout : UInt<32> @[booth_div_substep.scala 26:20]
    node _T_1 = asUInt(io.acc) @[booth_div_substep.scala 28:24]
    node _T_2 = shl(_T_1, 1) @[booth_div_substep.scala 28:31]
    shiftedA <= _T_2 @[booth_div_substep.scala 28:14]
    node _T_3 = bits(io.Q, 31, 31) @[booth_div_substep.scala 29:25]
    shiftedA_LSB <= _T_3 @[booth_div_substep.scala 29:18]
    node _T_4 = asUInt(io.Q) @[booth_div_substep.scala 30:22]
    node _T_5 = shl(_T_4, 1) @[booth_div_substep.scala 30:29]
    shiftedQ <= _T_5 @[booth_div_substep.scala 30:14]
    inst as1 of addsub_32 @[booth_div_substep.scala 32:21]
    as1.clock <= clock
    as1.reset <= reset
    wire sub_temp : UInt<32> @[booth_div_substep.scala 34:24]
    as1.io.cin <= UInt<1>("h01") @[booth_div_substep.scala 36:16]
    as1.io.onesComp_ip <= int_ip @[booth_div_substep.scala 37:24]
    node hi = bits(shiftedA, 31, 1) @[booth_div_substep.scala 38:30]
    node _T_6 = cat(hi, shiftedA_LSB) @[Cat.scala 30:58]
    as1.io.i0 <= _T_6 @[booth_div_substep.scala 38:15]
    sub_temp <= as1.io.sum @[booth_div_substep.scala 39:14]
    node _T_7 = bits(sub_temp, 31, 31) @[booth_div_substep.scala 42:19]
    node _T_8 = eq(_T_7, UInt<1>("h01")) @[booth_div_substep.scala 42:24]
    when _T_8 : @[booth_div_substep.scala 42:32]
      shiftedQ_LSB <= UInt<1>("h00") @[booth_div_substep.scala 43:22]
      node hi_1 = bits(shiftedA, 31, 1) @[booth_div_substep.scala 44:37]
      node _T_9 = cat(hi_1, shiftedA_LSB) @[Cat.scala 30:58]
      Aout <= _T_9 @[booth_div_substep.scala 44:22]
      skip @[booth_div_substep.scala 42:32]
    else : @[booth_div_substep.scala 45:16]
      shiftedQ_LSB <= UInt<1>("h01") @[booth_div_substep.scala 46:22]
      Aout <= sub_temp @[booth_div_substep.scala 47:22]
      skip @[booth_div_substep.scala 45:16]
    node _T_10 = asSInt(Aout) @[booth_div_substep.scala 50:25]
    io.next_acc <= _T_10 @[booth_div_substep.scala 50:17]
    node hi_2 = bits(shiftedQ, 31, 1) @[booth_div_substep.scala 51:32]
    node _T_11 = cat(hi_2, shiftedQ_LSB) @[Cat.scala 30:58]
    node _T_12 = asSInt(_T_11) @[booth_div_substep.scala 51:53]
    io.next_Q <= _T_12 @[booth_div_substep.scala 51:17]
    
